# bootctl
# Autogenerated from man page /usr/lib/jvm/default/man/man1/bootctl.1.gz
complete -c bootctl -l esp-path --description 'Path to the EFI System Partition (ESP).'
complete -c bootctl -l boot-path --description 'Path to the Extended Boot Loader partition, as defined in the \\m[blue]Boot Lo…'
complete -c bootctl -s p -l print-esp-path --description 'This option modifies the behaviour of status.'
complete -c bootctl -l print-boot-path --description 'This option modifies the behaviour of status.'
complete -c bootctl -l no-variables --description 'Do not touch the firmware\\*(Aqs boot loader list stored in EFI variables.'
complete -c bootctl -l no-pager --description 'Do not pipe output into a pager.'
complete -c bootctl -s h -l help --description 'Print a short help text and exit.'
complete -c bootctl -l version --description 'Print a short version string and exit.'

