# btrfs-rescue
# Autogenerated from man page /usr/lib/jvm/default/man/man8/btrfs-rescue.8.gz
complete -c btrfs-rescue -s y --description '.'
complete -c btrfs-rescue -s v --description '.'
complete -c btrfs-rescue -s h --description '.'

