# cgdisk
# Autogenerated from man page /usr/lib/jvm/default/man/man8/cgdisk.8.gz
complete -c cgdisk -s a --description 'free space: Instead of using ncurses, when -a is used cgdisk uses a ">" symbo…'

