# cinnamon-settings
# Autogenerated from man page /usr/lib/jvm/default/man/man1/cinnamon-settings.1.gz
complete -c cinnamon-settings -s h -l help --description 'Print a help text describing the supported command-line options, and then exi…'
complete -c cinnamon-settings -s s -l sort --description 'Specific to the \'download\' tab (see below) for applets, desklets, extensions …'
complete -c cinnamon-settings -s t -l tab --description 'Select the tab to open in the settings.'

