# createPYMB
# Autogenerated from man page /usr/lib/jvm/default/man/man1/createPYMB.1.gz
complete -c createPYMB -s b --description 'If not specified, it will read system default pybase. mb.'
complete -c createPYMB -s f --description 'If not specified, it will read user default PhraseMBFile, which is ~/.'
complete -c createPYMB -s s --description 'If specified, it will read PhraseMBFile as system format, otherwise will read…'
complete -c createPYMB -s h --description 'display help and exit.'

