# devlink-region
# Autogenerated from man page /usr/lib/jvm/default/man/man8/devlink-region.8.gz
complete -c devlink-region -s V --description '.'
complete -c devlink-region -s n --description 'devlink region show [  DEV/REGION  ] devlink region del  DEV/REGION  snapshot…'

