# expr
# Autogenerated from man page /usr/lib/jvm/default/man/man1/expr.1.gz
complete -c expr -l help --description 'display this help and exit.'
complete -c expr -l version --description 'output version information and exit .'

