# false
# Autogenerated from man page /usr/lib/jvm/default/man/man1/false.1.gz
complete -c false -l help --description 'display this help and exit.'
complete -c false -l version --description 'output version information and exit.'

