# fcitx
# Autogenerated from man page /usr/lib/jvm/default/man/man1/fcitx.1.gz
complete -c fcitx -s r --description 'replace existing fcitx.'
complete -c fcitx -s d --description 'run as daemon(default).'
complete -c fcitx -s D --description 'don\'t run as daemon.'
complete -c fcitx -o 's[sleep' --description 'override delay start time in config file, 0 for immediate start.'
complete -c fcitx -s u -l 'ui[ui' --description 'force to use specified user interface.'
complete -c fcitx -l 'enable[addon' --description 'specify a comma separated list for addon that will override the enable option.'
complete -c fcitx -l 'disable[addon' --description 'specify a comma separated list for addon that will explicitly disabled, prior…'
complete -c fcitx -s v --description 'display the version information and exit.'
complete -c fcitx -s h --description 'display help and exit ENVIRONMENT.'

