# fcitx-remote
# Autogenerated from man page /usr/lib/jvm/default/man/man1/fcitx-remote.1.gz
complete -c fcitx-remote -s c --description 'inactivate input method.'
complete -c fcitx-remote -s o --description 'activate input method.'
complete -c fcitx-remote -s r --description 'reload fcitx config.'
complete -c fcitx-remote -s t --description 'switch between active/inactive.'
complete -c fcitx-remote -s s --description 'switch to the input method uniquely identified by imname.'
complete -c fcitx-remote -s h --description 'display help and exit FILES fcitx will create socket at /tmp/fcitx-socket-<di…'

