# fontimage
# Autogenerated from man page /usr/lib/jvm/default/man/man1/fontimage.1.gz
complete -c fontimage -l help --description 'Provide a description with a list of the available options.'
complete -c fontimage -l width --description 'Specifies the width of the output image.'
complete -c fontimage -l height --description 'Specifies the height of the output image.'
complete -c fontimage -l pixelsize --description 'Specifies the pixelsize used to display the text.'
complete -c fontimage -l text --description 'Specifies a line of text to be displayed.  The string must be in UTF-8.'
complete -c fontimage -s o --description 'Specifies the output filename for the image.'
complete -c fontimage -l usage --description 'Display the usage description.'
complete -c fontimage -l version --description 'Display the current version SEE ALSO fontforge (1).'

