# getcifsacl
# Autogenerated from man page /usr/lib/jvm/default/man/man1/getcifsacl.1.gz
complete -c getcifsacl -s v --description 'Print version number and exit.'
complete -c getcifsacl -s r --description 'Display a security descriptor in raw mode.'

