# gperl
# Autogenerated from man page /usr/share/man/man1/gperl.1.gz
complete -c gperl -s h -l help --description 'Print help information with a short explanation of options to standard output.'
complete -c gperl -s v -l version --description 'Print version information to standard output.'

