# grub-emu
# Autogenerated from man page /usr/lib/jvm/default/man/man1/grub-emu.1.gz
complete -c grub-emu -s d -l directory --description 'use GRUB files in the directory DIR [default=//boot/grub].'
complete -c grub-emu -s H -l hold --description 'wait until a debugger will attach.'
complete -c grub-emu -s m -l device-map --description 'use FILE as the device map [default=//boot/grub/device. map].'
complete -c grub-emu -l memdisk --description 'use FILE as memdisk.'
complete -c grub-emu -s r -l root --description 'Set root device.'
complete -c grub-emu -s v -l verbose --description 'print verbose messages.'
complete -c grub-emu -s '?' -l help --description 'give this help list.'
complete -c grub-emu -l usage --description 'give a short usage message.'
complete -c grub-emu -s V -l version --description 'print program version.'

