# gst-launch-1
# Autogenerated from man page /usr/share/man/man1/gst-launch-1.0.1.gz
complete -c gst-launch-1 -l gst-version --description 'Prints the version string of the GStreamer core library.'
complete -c gst-launch-1 -l gst-fatal-warnings --description 'Causes GStreamer to abort if a warning message occurs.'
complete -c gst-launch-1 -l gst-debug --description 'A comma separated list of category_name:level pairs to specify debugging leve…'
complete -c gst-launch-1 -l gst-debug-level --description 'Sets the threshold for printing debugging messages.'
complete -c gst-launch-1 -l gst-debug-no-color --description 'GStreamer normally prints debugging messages so that the messages are color-c…'
complete -c gst-launch-1 -l gst-debug-color-mode --description 'GStreamer normally prints debugging messages so that the messages are color-c…'
complete -c gst-launch-1 -l gst-debug-disable --description 'Disables debugging.'
complete -c gst-launch-1 -l gst-debug-help --description 'Prints a list of available debug categories and their default debugging level.'
complete -c gst-launch-1 -l gst-plugin-spew --description 'GStreamer info flags to set Enable printout of errors while loading GStreamer…'
complete -c gst-launch-1 -l gst-plugin-path --description 'Add directories separated with \':\' to the plugin search path.'
complete -c gst-launch-1 -l gst-plugin-load --description 'Preload plugins specified in a comma-separated list.'

