# libinput
# Autogenerated from man page /usr/lib/jvm/default/man/man1/libinput.1.gz
complete -c libinput -l help --description 'Print help and exit.'
complete -c libinput -l version --description 'Print the version and exit COMMANDS.'

