# lz4cat
# Autogenerated from man page /usr/share/man/man1/lz4cat.1.gz
complete -c lz4cat -o B4 -o B5 -o B6 -o B7 --description '.'
complete -c lz4cat -o 'i#' --description 'Minimum evaluation time in seconds [1-9] (default : 3).'

