# mkfs
# Autogenerated from man page /usr/lib/jvm/default/man/man8/mkfs.xfs.8.gz
complete -c mkfs -o bcdpl --description 'A file may be a regular file, a block special file, a character special file,…'

