# ndctl-disable-region
# Autogenerated from man page /usr/lib/jvm/default/man/man1/ndctl-disable-region.1.gz
complete -c ndctl-disable-region -l region --description '.'
complete -c ndctl-disable-region -s b -l bus --description '.'

