# nemo
# Autogenerated from man page /usr/lib/jvm/default/man/man1/nemo.1.gz
complete -c nemo -l check --description 'Perform a quick set of self-check tests.'
complete -c nemo -l geometry --description 'Create the initial window with the given geometry.'
complete -c nemo -l tabs --description 'Open URIs in tabs.'
complete -c nemo -l no-default-window --description 'Only create windows for explicitly specified URIs.'
complete -c nemo -l no-desktop --description 'Ignored - left for compatibility only.'
complete -c nemo -l fix-cache --description 'Repair the user thumbnail cache - this can be useful if you\'re having trouble…'
complete -c nemo -l quit --description 'Quit Nemo.'
complete -c nemo -l help --description 'Show a summary of options.'
complete -c nemo -l version --description 'Show Nemo\' version.'
complete -c nemo -s c --description '.'
complete -c nemo -s g --description '.'
complete -c nemo -s t --description '.'
complete -c nemo -s n --description '.'
complete -c nemo -s q --description '.'

