# pacmd
# Autogenerated from man page /usr/lib/jvm/default/man/man1/pacmd.1.gz
complete -c pacmd -s h -l help --description 'Show help.'
complete -c pacmd -l version --description 'Show version information.'

