# pathchk
# Autogenerated from man page /usr/lib/jvm/default/man/man1/pathchk.1p.gz
complete -c pathchk -s C --description 'noclobber ) option added to the shell, replaces the mktemp , validfnam , and …'

