# pipewire-monitor
# Autogenerated from man page /usr/lib/jvm/default/man/man1/pipewire-monitor.1.gz
complete -c pipewire-monitor -s h -l help --description 'Show help.'
complete -c pipewire-monitor -l version --description 'Show version information.  AUTHORS The PipeWire Developers <https://github.'

