# pipewire
# Autogenerated from man page /usr/lib/jvm/default/man/man1/pipewire.1.gz
complete -c pipewire -s h -l help --description 'Show help.'
complete -c pipewire -s v -l version --description 'Show version information.'
complete -c pipewire -s n -l name --description 'Set the daemon name (Default pipewire-1).'

