# rmid-openjdk11
# Autogenerated from man page /usr/lib/jvm/default/man/man1/rmid-openjdk11.1.gz
complete -c rmid-openjdk11 -o Coption --description 'br Specifies an option that is passed as a command-line argument to each chil…'
complete -c rmid-openjdk11 -o Joption --description 'br Specifies an option that is passed to the Java interpreter running RMID.'
complete -c rmid-openjdk11 -o 'J-Dsun.rmi.activation.execPolicy' --description 'br Specifies the policy that RMID employs to check commands and command-line …'
complete -c rmid-openjdk11 -o log --description 'br Specifies the name of the directory the activation system daemon uses to w…'
complete -c rmid-openjdk11 -o port --description 'br Specifies the port the registry uses.'
complete -c rmid-openjdk11 -o stop --description '.'

