# rpc
# Autogenerated from man page /usr/lib/jvm/default/man/man8/rpc.statd.8.gz
complete -c rpc -l no-syslog --description 'Causes  rpc.'
complete -c rpc -s '?' --description 'Causes  rpc. statd to display usage information on  stderr and then exit.'
complete -c rpc -l no-notify --description 'Prevents  rpc.'
complete -c rpc -l name --description 'Specifies the bind address used for RPC listener sockets.'
complete -c rpc -l outgoing-port --description 'Specifies the source port number the  sm-notify command should use when sendi…'
complete -c rpc -l nlm-port --description 'Specifies the port number that  lockd should listen on for  NLM requests.'
complete -c rpc -l nlm-udp-port --description 'Specifies the UDP port number that  lockd should listen on for  NLM requests.'

