# sfddiff
# Autogenerated from man page /usr/lib/jvm/default/man/man1/sfddiff.1.gz
complete -c sfddiff -l help --description 'Provide a description with a list of the available options.'
complete -c sfddiff -l ignorehints --description 'Suppress the reporting of hint/instruction differences.'
complete -c sfddiff -l ignoregpos --description 'Suppress the reporting of kerning (and other \'gpos\') differences.'
complete -c sfddiff -l ignoregsub --description 'Suppress the reporting of ligature (and other \'gsub\') differences.'
complete -c sfddiff -l ignorenames --description 'Suppress the reporting of name string differences.'
complete -c sfddiff -l ignorebitmaps --description 'Suppress the reporting of bitmap differences.'
complete -c sfddiff -l exact --description 'Require outlines to match exactly.'
complete -c sfddiff -l warn --description 'Warn if the outlines/references are slightly different.'
complete -c sfddiff -l merge --description 'Store a merged version of the two fonts into the specified output file.'
complete -c sfddiff -l usage --description 'Display the usage description.'
complete -c sfddiff -l version --description 'Display the current version.  SEE ALSO fontforge(1).'

