# unzstd
# Autogenerated from man page /usr/share/man/man1/unzstd.1.gz
complete -c unzstd -l maxdict --description 'Limit dictionary to specified size (default: 112640).'
complete -c unzstd -o 'B#' --description 'Split input files in blocks of size # (default: no split).'
complete -c unzstd -l dictID --description 'A dictionary ID is a locally unique ID that a decoder can use to verify it is…'
complete -c unzstd -l train-cover --description 'Select parameters for the default dictionary builder algorithm named cover.'
complete -c unzstd -l train-fastcover --description 'Same as cover but with extra parameters f and accel and different default val…'
complete -c unzstd -l train-legacy --description 'Use legacy dictionary builder algorithm with the given dictionary selectivity…'
complete -c unzstd -o 'e#' --description 'benchmark file(s) using multiple compression levels, from -b# to -e# (inclusi…'
complete -c unzstd -o 'i#' --description 'minimum evaluation time, in seconds (default: 3s), benchmark mode only.'
complete -c unzstd -l block-size --description 'cut file(s) into independent blocks of size # (default: no block).'
complete -c unzstd -l priority --description 'set process priority to real-time Output Format: CompressionLevel#Filename : …'
complete -c unzstd -l zstd --description 'zstd provides 22 predefined compression levels.'

