# xdg-su
# Autogenerated from man page /usr/lib/jvm/default/man/man1/xdg-su.1.gz
complete -c xdg-su -s s --description 'run command via sudo.'
complete -c xdg-su -s x --description 'run command via su.  If sudo is default.'
complete -c xdg-su -l help --description 'Show command synopsis.'
complete -c xdg-su -l manual --description 'Show this manualpage.'
complete -c xdg-su -l version --description 'Show the xdg-utils version information.'

